prismatic-io/embedded

package-lock.json, package.json, src/lib/setConfigVars.ts
`setConfigVars` is referencing the incorrect `postMessage` method, should be using the custom postMessage instead of the window.postMessage.
=> Hotfix - setConfigVars postMessage Reference

package-lock.json, package.json, src/types/phrases.ts
Make `filterBar.refreshButton` and `filterBar.refreshTooltip` generalized, instead of name-spaced. This allows us to use these in different screens of the application. Since these are name-spaced, they will work if the user had previously opted to setting these translations.
=> Translation - FilterBar Refresh Button & Tooltip

package-lock.json, package.json, src/index.ts, src/lib/authenticate.ts, src/lib/configureInstance.ts, src/lib/graphqlRequest.ts, src/lib/setConfigVars.ts, src/lib/showComponent.ts, src/lib/showComponents.ts, src/lib/showDesigner.ts, src/lib/showIntegrations.ts, src/lib/showLogs.ts, src/lib/showMarketplace.ts, src/types/index.ts, src/types/screenConfiguration.ts
Add additional exported types to package for users consumption. Requested here #5, below are the types added:
- Phrases
- Translation
- SelectorOptions
- PopoverOptions
- Options
- Filters
- Theme
- ConfigVar
- ConnectionConfigVar
- ConnectionConfigVarInput
- DefaultConfigVar
- DefaultConfigVarInput
- ConfigurationWizardConfiguration
- InitializingConfiguration
- InstanceScreenConfiguration
- MarketplaceConfiguration
- ScreenConfiguration
- TriggerDetails
- InitProps
- ShowMarketplaceProps
- ShowLogsProps
- ShowIntegrationsProps
- ShowDesignerProps
- ShowComponentsProps
- ShowComponentProps
- SetConfigVarsProps
- GraphqlRequestProps
- ConfigureInstanceProps
- AuthenticateProps
=> Types - Export Additional Interfaces, Enums, Types.

src/types/phrases.ts
Add translations to configuration wizard and listing page fallbacks.
=> Translations - Configuration Wizard & Listing Page Fallbacks

package-lock.json, package.json, webpack.config.js
> The problem is, I think, this target: 'node' in your webpack.config.js. This states basically that Webpack may assume that the bundle will be running in a node-like environment, where globals like global and require are provided by the environment. Unless otherwise specified, Webpack assumes a browser environment and rewrites global to point to window. Your configuration disables this rewriting. 
>
> You could either remove target: 'node' from your config, or explicitly enable global rewriting by adding node: {global: true} to your config object.
=> Hotfix - Global Rewrite for Browser Envs

package-lock.json, package.json
Developers will likely want to be able to view spectral type definitions from within their editor. This allows them to do that, without causing build sizes to increase, etc.
=> Make spectral a dependency rather than dev dependency

package-lock.json, package.json, src/lib/init.ts, src/utils/iframe.ts
`iframe.onload` guaranteed that the iframe existed in the DOM however the React app was never hydrated prior to sending events over. Embedded now waits until the React app sends an initialized event before sending it's initial configuration.
This also assures that subsequent calls to prismatic.init update the configuration
=> Fix initialization of embedded state

.tool-versions, package-lock.json, package.json, src/lib/index.ts, src/lib/init.ts, src/lib/showMarketplace.ts, src/types/filters.ts, src/types/index.ts, src/types/screenConfiguration.ts
Add filters to embedded SDK for integrations, marketplace, and components
- moved includeActiveIntegrations from screen configurations to filters
- added integrations filters
- added components filters
- added marketplace filters (deprecated main level filters)
- added a new way to defaults (since methods have a bug that will always overwrite the init options)
=> Add filters to embedded SDK for integrations, marketplace, and components

package-lock.json, package.json
Starting in the `2.0.0` release of `@prismatic-io/embedded`, the default value for `screenConfiguration.marketplace.configuration` changes from `always-show-details` to `allow-details`.  To keep existing behavior, explicitly set the configuration value to `always-show-details`.
https://prismatic.io/docs/embedding-marketplace/#integration-configuration-detail-screen
=> Bump @prismatic-io/embedded to 2.0.0

package-lock.json, package.json, src/lib/authenticate.ts, src/lib/graphqlRequest.ts, src/lib/init.ts, src/state.ts, src/utils/assertInit.ts, src/utils/iframe.ts
Updates the references to the shared state so that calls to `prismatic.init` will always start from the fresh default state, and calls to `setIframe` do not mutate the shared state but simply pass the merged state to the iframe.
=> Fix subsequent calls to embedded methods

package-lock.json, package.json, src/lib/init.ts, src/state.ts, src/utils/iframe.ts
This uses [WebFontLoader](https://github.com/typekit/webfontloader) to load custom Google fonts for use in embedded
Example usage:
```ts
prismatic.init({
fontConfiguration: {
google: {
families: ["Inter"],
},
},
});
```
=> Add support for custom google fonts

src/utils/iframe.ts
If you initialize the Prismatic embedded SDK with a URL that has a trailing slash (i.e. `https://app.ap-southeast-2.prismatic.io/` vs `https://app.ap-southeast-2.prismatic.io`), an `iframe` is built with double-slashes (i.e. `https://app.ap-southeast-2.prismatic.io//integration-marketplace?embed=....`). The double-slashes result in a 404.
Rather than using string concatenation for iframe `src` property, let's use `url-join`, which handles trailing slashes for you.
=> Use url-join to generate iframe src properties, to account for trailing slashes

package-lock.json, package.json, src/types/screenConfiguration.ts
Adds the following properties to `ScreenConfiguration["configurationWizard"]` for disabling logs and step results for integration deployed through embedded.
```ts
/**
* Disable logs on integrations deployed via marketplace
* @default "never"
*/
logsDisabled?: "always" | "never" | "optional";
/**
* Disable step results on integrations deployed via marketplace
* @default "never"
*/
stepResultsDisabled?: "always" | "never" | "optional";
```
=> Add ability to configure disabling logs and step results

package-lock.json, package.json, src/lib/index.ts, src/lib/init.ts, src/types/filters.ts
Add strictMatchFilterQuery to allow embedded developers to prioritize includeActiveIntegrations over filters.
=> Add strictMatchFilterQuery and bump to v2.3.0

package-lock.json, package.json, src/lib/setConfigVars.ts, src/types/configVars.ts, src/types/index.ts
Our setConfigVars method's main property is configVars. This property is used in several different places within the application, and it may also be accessed by external users. Exposing this property allows us to avoid using type indexes or repeating type aliases when using or creating the config variables for setConfigVars method.
=> Expose ConfigVars Type

example-embedded-app/package-lock.json, example-embedded-app/package.json
**Issue:**
An issue was discovered in PostCSS before 8.4.31. It affects linters using PostCSS to parse external Cascading Style Sheets (CSS). There may be \r discrepancies, as demonstrated by @font-face{ font:(\r/*);} in a rule.
This vulnerability affects linters using PostCSS to parse external untrusted CSS. An attacker can prepare CSS in such a way that it will contains parts parsed by PostCSS as a CSS comment. After processing by PostCSS, it will be included in the PostCSS output in CSS nodes (rules, properties) despite being originally included in a comment.
https://github.com/prismatic-io/embedded/security/dependabot/9
**Solution:**
Initially, I attempted to update NextJS from v12.1.6 to v12.3.4 (which is the latest non-breaking change version), but this did not solve the issue …
=> PostCSS - Vulnerability Fix

package-lock.json, package.json, src/index.ts, src/utils/popover.ts
Under certain circumstances, it is helpful to be able to close an open popover from an application that embeds Prismatic. This exposes the `closePopover()` function.
=> Expose closePopover() function

package-lock.json, package.json, src/lib/init.ts, src/types/screenConfiguration.ts
https://app.shortcut.com/prismatic/story/18009/add-ability-to-hide-search-inputs-from-embeddable-screens-due-to-translation-searching-difficiencies
=> Adds Hide Search Check for Dynamic Phrases & Hides ActiveIntegrationsFilter

example-embedded-app/pages/examples/custom-component-list.md, example-embedded-app/pages/examples/custom-component-list.tsx
This embedded example shows how someone could query the Prismatic API for a list of components, and display those components in custom UI elements. This example is often used for marketing, to display to customers a list of components that they could use in the embedded designer.
=> Add an example showing how to display components as custom UI elements

src/lib/authenticate.ts, src/lib/showDesigner.ts, src/lib/showIntegrations.ts, src/state.ts, src/utils/assertEmbeddedDesigner.ts, src/utils/assertInit.ts
Currently, if you omit a `prismatic.authenticate()` call, or if your call fails but is not caught, a `showMarketplace()` or similar call will still inject an `iframe` but the iframe will contain a 404 screen. This makes it so a successful `prismatic.authenticate()` call must run before subsequent calls are allowed, and an instructive error is thrown if you attempt to call `showMarketplace()` prior to `authenticate()`.
=> Throw an error if showMarketplace() or similar functions are called before a successful authenticate()

package-lock.json, package.json
This updates the `@prismatic-io/translations` to its latest version to allow for dynamic translations of integration names, config variables, and more.
=> Bump @prismatic-io/translations dependency

example-embedded-app/package-lock.json, package-lock.json, package.json, src/lib/init.ts, src/state.ts
**Issue:**
We need a method to pre-load assets and connections when making calls within the embedded SDK.
**Tried Solutions:**
- `dns-prefetch`: Unnecessary because DNS resolution to obtain the cached IP address has already been done.
- `preconnect`: Establishing a `preconnect` from the top frame origin for resources referenced in the iframe will not function properly due to the differing origins between the top frame and the iframe.
- `preload`: This method only preloads specified resources, which is ineffective for our case since our resources are bundled with different hashes. To make this work, we would need to create a remote-fetchable manifest that references these resources. This approach does not seem worthwhile.
- `prerender`: Deprecating in Chrome and Edge, and already …
=> Preload the application assets and cache connections

example-embedded-app/package-lock.json, package-lock.json, package.json, src/types/configVars.ts
This prepares embedded for an upcoming change where the `INSTANCE_CONFIGURATION_LOADED` event will now include config variable `id` and `status` (for OAuth connection config variables). The `ConnectionConfigVar` type already included `status`, but needed the other properties a config variable has (defined in `BaseConfigVar`).
=> Config variables emitted with marketplace events will now include ID and OAuth status

example-embedded-app/package-lock.json, package-lock.json, package.json, src/types/conditionalLogic.ts, src/types/filters.ts
This removes embedded's dependency on `@prismatic-io/spectral`.
Currently, we import spectral for conditional logic TypeScript types. We pare down the types Spectral presents to a subset of types that we require, and those types are used when filtering integrations, marketplace offerings and components. The types we actually need in embedded are simple. This copies the types we require into this repo, and removes the unnecessary dependency on spectral.
=> Remove Spectral dependency

example-embedded-app/pages/api/prismatic-auth.tsx, example-embedded-app/prismatic/types.ts, example-embedded-app/src/usePrismaticAuth.ts
It's best practice to generate short-lived JWTs for the embedded markeplace, and to refresh the tokens before they expire. This adds a new config setting to the example embedded app, `tokenValidSeconds`, which determines how many seconds the token is valid for. The `usePrismaticAuth` hook is configured now to fetch a new token 30 seconds before the token expires. When a new token is detected, the `useEffect` within that hook re-issues a `prismatic.authenticate()` call with the new token.
=> Automatically refresh the auth token in the example app

example-embedded-app/package-lock.json, example-embedded-app/pages/api/prismatic-auth.tsx, example-embedded-app/prismatic/config.ts.template, example-embedded-app/prismatic/types.ts
You can now add a `customer_name` claim to a signed JWT. When `customer_name` is present, and the customer specified by the `customer` external ID claim does not yet exist, the a new customer record will be automatically created.
This demonstrates how to add a `customer_name` claim to the signed JWT in the example app.
=> Add customer upsert to example app
