- package-lock.json
- package.json
- src/types/phrases.ts
Add the ability to modify component listings, component and integrations listing translations
> Translations - Integrations & Components 

- .tool-versions
- package-lock.json
- package.json
- src/index.ts
- src/lib/index.ts
- src/lib/showLogs.ts
Ability to look at all logs for customer across all instances in embedded.
> Logs - Add ability to see all customers logs

- package-lock.json
- package.json
Addresses https://github.com/prismatic-io/embedded/security/dependabot/1
> Bump Webpack to 5.76.2

- package-lock.json
- package.json
- src/types/phrases.ts
Add all listing page empty route translations.
> Translations - Empty Route Translations 

- package-lock.json
- package.json
- src/lib/showMarketplace.ts
- src/types/screenConfiguration.ts
Enable all active integrations by default.
> Marketplace - Enable all active integrations by default

- package-lock.json
- package.json
- src/index.ts
- src/lib/authenticate.ts
- src/lib/setConfigVars.ts
- src/types/index.ts
- src/types/postMessage.ts
- src/utils/iframe.ts
- src/utils/popover.ts
- src/utils/postMessage.ts
- Abstract post message types into own area.
- Add new user configuration types
```
USER_CONFIGURATION_CLOSED
USER_CONFIGURATION_DELETED
USER_CONFIGURATION_DEPLOYED
USER_CONFIGURATION_LOADED
USER_CONFIGURATION_OPENED
```
> Events - Post Message Event Abstraction & New User Configuration Events

- package-lock.json
- package.json
- src/index.ts
- src/lib/index.ts
- src/lib/showMarketplace.ts
- Add named export to be used in UMD library `prismatic` in browser.
- Default popover true if no options added.
- Check for undefined properties, fallback to empty object spread.
> Name Exports, Default Popover, & Undefined Property Checks

- package-lock.json
- package.json
- src/types/postMessage.ts
Reset interfaces back to originals for instance post message events.
> Types - InstanceConfigurationData Types

- package-lock.json
- package.json
- src/types/index.ts
- src/types/postMessage.ts
Export additional type InstanceConfigurationLoadedData from package.
> Types - Export Additional Type InstanceConfigurationLoadedData

- package-lock.json
- package.json
- src/lib/index.ts
- src/lib/showDashboard.ts
- src/types/index.ts
- src/types/screenConfiguration.ts
Add ability as a customer, the overview of integration that are activate and any relevant/recent updates regarding those integrations.... ie failures, logs, executions, etc...
Complete list of new screens available to customer marketplace admins.
- Summary
- Integrations
- Components
- Instances
- Logs
- Monitors
- Users
- Executions
> Add showDashboard to embedded

- package-lock.json
- package.json
- src/types/screenConfiguration.ts
Add marketplace to screen configuration for customer dashboard.
> Dashboard Marketplace Tab

- package-lock.json
- package.json
- src/types/screenConfiguration.ts
Add credentials to hide tab screen configurations in dashboard.
> Dashboard - Ability to hide Credentials tab 

- example-embedded-app/package-lock.json
- example-embedded-app/package.json
- example-embedded-app/pages/examples/embedded-dashboard.md
- example-embedded-app/pages/examples/embedded-dashboard.tsx
- example-embedded-app/pages/examples/embedded-designer.md
- example-embedded-app/pages/examples/embedded-designer.tsx
- example-embedded-app/src/layouts/SidebarLayout/Sidebar/SidebarMenu.tsx
Bump @prismatic-io/embedded in example app to 2.0.2.
Add example of showDashboard() with hiding tabs
Add example of filtering components in embedded designer
> Update example app to use embedded 2.x

- src/lib/index.ts
- src/types/filters.ts
- src/types/screenConfiguration.ts
Updates deprecation notes for several functions and parameters that they will be removed in 3.0.0 (not 2.0.0).
> Several functions and parameters will be deprecated in 3.0.0

- package-lock.json
- package.json
- src/types/translation.ts
Removes Dynamic Phrases type and relies on Translation package instead
> Removes Dynamic Phrases 

- .tool-versions
- package-lock.json
- package.json
- src/lib/authenticate.ts
- src/lib/graphqlRequest.ts
- src/lib/init.ts
- src/utils/assertEmbeddedDesigner.ts
- src/utils/iframe.ts
- Update the NodeJS version for the frontend app so that npm linking is possible. 
- Preload iframe script conditional to prevent possible duplication of dom elements.
> Update node version & preload iframe conditional

- package-lock.json
- package.json
- src/lib/configureInstance.ts
- src/lib/index.ts
- src/types/index.ts
Add ability to query based from `integrationId` and `instanceId` properties in `configureInstance` method.
> Configure Instance - Add `integrationid, instanceId` props to method

- example-embedded-app/package-lock.json
- package-lock.json
- package.json
- src/types/index.ts
- src/types/screenConfiguration.ts
Add configure instance configuration options.
> Screen Configuration - Add configure instance configuration options

- example-embedded-app/package-lock.json
- package-lock.json
- package.json
- src/types/screenConfiguration.ts
Add an option to hide the pause/unpause button on the instance config screen.
> Add an option to hide the pause/unpause button

- example-embedded-app/package-lock.json
- example-embedded-app/package.json
> Bump Axios in example embedded app

- example-embedded-app/pages/examples/custom-ui-elements.tsx
This updates the embedded example app's custom marketplace UI example to use newer optimized `marketplaceIntegrations` query.
> Update custom UI example with new optimized marketplaceIntegrations query
